= Ruling Database Testing with DBUnit Rules
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:source-highlighter: coderay
:sectlink:
:numbered:
:doctype: book
:toc: preamble
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

In this article I'm going to talk about https://github.com/rmpestano/dbunit-rules[DBUnit Rules^], a small open source project I maintain which aims to simplify database testingfootnote:[In the context of this article, database testing stands for http://junit.org/[JUnit^] integration tests which depend on a *relational* database so application business logic that depend on a database can be tested without mocking.].

== Introduction

`DBUnit Rules` integrates http://junit.org/[JUnit^] and http://dbunit.sourceforge.net/[DBUnit^] through https://github.com/junit-team/junit4/wiki/Rules[JUnit rules^] and, in case of https://docs.jboss.org/weld/reference/latest/en-US/html_single/[CDI^] based tests, a https://docs.oracle.com/javaee/6/tutorial/doc/gkhjx.html[CDI interceptor^]. This powerful combination lets you easily prepare the database state for testing through *xml, json, xls or yaml* files.

Most inspiration of DBUnit Rules was taken from https://docs.jboss.org/author/display/ARQ/Persistence[Arquillian extension persistence^] a library for database http://stackoverflow.com/questions/15524687/in-container-testing-with-junit[in-container integration tests^]. 


Source code for the upcoming examples can be found at github here: https://github.com/rmpestano/dbunit-rules-sample

== Setup DBUnit Rules

First thing to do is to add DBunit Rules core module to your test classpath:


----
include::{basedir}/pom.xml[tags=dbunit-rules]
----

Secondly we need a database, for testing I recommend http://hsqldb.org/[HSQLDB^] which is a very fast in-memory database, here is its maven dependency:


----
include::{basedir}/pom.xml[tags=hsqldb]
----

Later A JPA provider will be needed, in this case Hibernate will be used:

----
include::{basedir}/pom.xml[tags=hibernate]
---- 
 
And the entity manager persistence.xml:

.src/test/resources/META-INF/persistence.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
    <persistence-unit name="rulesDB" transaction-type="RESOURCE_LOCAL">

	    <provider>org.hibernate.ejb.HibernatePersistence</provider>
	    <class>com.github.dbunit.rules.sample.User</class>

	    <properties>
		<property name="hibernate.dialect" value="org.hibernate.dialect.HSQLDialect" />
		<property name="javax.persistence.jdbc.driver" value="org.hsqldb.jdbcDriver" />
		<property name="javax.persistence.jdbc.url" value="jdbc:hsqldb:mem:test;DB_CLOSE_DELAY=-1" />
		<property name="javax.persistence.jdbc.user" value="sa" />
		<property name="javax.persistence.jdbc.password" value="" />
		<property name="hibernate.hbm2ddl.auto" value="create-drop" />
		<property name="hibernate.show_sql" value="true" />
	    </properties>

    </persistence-unit>

</persistence>
----

and finally the JPA entity which our tests will work on:

[source,java,linenums]
----
@Entity
public class User {

    @Id
    @GeneratedValue
    private long id;

    private String name;
----

Now we are ready to rule our database tests!

== Example

Create a yaml file which will be used to prepare database (with two users) before the test:

.src/test/resources/dataset/users.yml
----
include::{datasetdir}/users.yml[]
----
<1> Table name is followed by `:`, we can have multiple tables in the same file.
<2> Table rows are separated by `-`.

WARNING: Be careful with *spaces*, wrong identation can lead to invalid dataset (principally in `yaml` datasets).   

TIP: For more dataset examples, https://github.com/rmpestano/dbunit-rules/tree/master/core/src/test/resources/datasets[look here^].

And the JUnit test:

[source, java, linenums]
----
include::{testdir}/DBUnitRulesCoreTest.java[tags=declaration;sample]
}
----
<1> EntityManagerProvider is a JUnit rule that initializes a JPA entity manager before each *test class*. `rulesDB` is the name of persistence unit;
<2> DBUnit rule reads *@DataSet* annotations and initializes database before each *test method*. This rule only needs a *JDBC* connection to be created.
<3> The dataSet configuration itself, https://github.com/rmpestano/dbunit-rules/blob/master/core/src/main/java/com/github/dbunit/rules/api/dataset/DataSet.java#L14[see here^] for all available configuration options. Note that you can provide a comma separated list of datasets names here. 
<4> *em()* is a shortcut (`import static com.github.dbunit.rules.util.EntityManagerProvider.em;`) for the EntityManager that was initialized by EntityManagerProvider rule. 
 
TIP: There is a lot of https://github.com/rmpestano/dbunit-rules/tree/master/core/src/test/java/com/github/dbunit/rules[example tests here^]. 

== Transactions 

EntityManagerProvider rule provides entity manager transactions so you can insert/delete entities in your tests:

[source, java, linenums]
----
include::{testdir}/DBUnitRulesCoreTest.java[tags=transaction]
----
<1> `tx()` is a shortcut for the entity manager transaction provided by EntityManagerProvider.

== Database assertion with ExpectedDataSet

Consider the following datasets:

.src/test/resources/dataset/users.yml
----
include::{datasetdir}/users.yml[]
----

and expected dataset:

.src/test/resources/dataset/expectedUser.yml
----
include::{datasetdir}/expectedUser.yml[]
----

And the following test:

[source, java, linenums]
----
include::{testdir}/DBUnitRulesCoreTest.java[tags=expected]
----
<1> Database state after test will be compared with dataset provided by `@ExpectedDataSet`.

[NOTE]
====
If database state is not equal then an assertion error is thrown, example imagine in test above we've deleted user with `id=2`, error would be:
-----
junit.framework.ComparisonFailure: value (table=USER, row=0, col=name) 
Expected :@dbunit
Actual   :@realpestano
 <Click to see difference>
	at org.dbunit.assertion.JUnitFailureFactory.createFailure(JUnitFailureFactory.java:39)
	at org.dbunit.assertion.DefaultFailureHandler.createFailure(DefaultFailureHandler.java:97)
	at org.dbunit.assertion.DefaultFailureHandler.handle(DefaultFailureHandler.java:223)
	at com.github.dbunit.rules.assertion.DataSetAssert.compareData(DataSetAssert.java:94)
-----
====

TIP: Since version _0.9.0_ (To be released at the time of writing) transactions will be able to be managed automatically at test level (useful for _expected datasets_ cause you don't assert db changes inside the test), see https://github.com/rmpestano/dbunit-rules/blob/master/core/src/test/java/com/github/dbunit/rules/TransactionIt.java#L46[example here^].


=== Regular expressions

Expected datasets also alow `regexp` in datasets:

.src/test/resources/dataset/expectedUsersRegex.yml
----
include::{datasetdir}/expectedUsersRegex.yml[]
----

[source, java, linenums]
----
include::{testdir}/DBUnitRulesCoreTest.java[tags=expected-regex]
----
<1> You don't need to initialize a dataset but can use `cleanBefore` to clear database before testing.

IMPORTANT: When you use a dataset like users.yml in @DataSet dbunit will use `CLEAN_INSERT` seeding strategy (by default) for all declared tables in dataset. This is why we didn't needed `cleanBefore` in any other example tests.

== Scriptable datasets

DBUnit Rules enables scripting in dataset for languages that implement JSR 233 - Scripting for the Java Platform, http://www.javaworld.com/article/2077792/java-se/scripting-on-the-java-platform.html[see this article^] for more information. 

For this example we will introduce another JPA entity:

[source,java,linenums]
----
include::{sourcedir}/Tweet.java[tags=tweet]
----

=== Javascript scriptable dataset

Following is a dataset which uses Javascript:

.src/test/resources/datasets/dataset-with-javascript.yml
----
include::{datasetdir}/dataset-with-javascript.yml[]
----
<1> `js:` prefix enables javascript in datasets.

and the junit test:

[source,java,linenums]
----
include::{testdir}/DBUnitRulesCoreTest.java[tags=scriptable-js]
----
<1> As we don't declared `User` table in dataset it will not be cleared by `CLEAN_INSERT` seeding strategy so we need cleanBefore to avoid conflict with other tests that insert users.
<2> Disabling constraints is necessary because `Tweet` table depends on `User`.

if we do not disable constraints we will receive the error below on dataset creation:

----
Caused by: org.dbunit.DatabaseUnitException: Exception processing table name='TWEET'
	at org.dbunit.operation.AbstractBatchOperation.execute(AbstractBatchOperation.java:232)
	at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
	at com.github.dbunit.rules.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:127)
	... 21 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: foreign key no parent; FK_OH8MF7R69JSK6IISPTIAOCC6L table: TWEET
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
---- 

TIP: If we declare `User` table in `dataset-with-javascript.yml` dataset we can remove `cleanBefore` and `disableConstraints` attributes. 

=== Groovy scriptable dataset

Javascript comes by default in JDK but you can use other script languages like `Groovy`, to do so you need to add it to test classpath:

.pom.xml
----
include::{basedir}/pom.xml[tags=groovy-all]
----

If Groovy is not present in classpath we'll receive a _warn message_ (maybe we should fail, what do you think?):

----
WARNING: Could not find script engine with name groovy in classpath
----

Here's our Groovy based dataset:

.src/test/resources/datasets/dataset-with-groovy.yml
----
include::{datasetdir}/dataset-with-groovy.yml[]
----
<1> `groovy:` prefix enables javascript in datasets.


And here is the test: 

[source,java,linenums]
----
include::{testdir}/DBUnitRulesCoreTest.java[tags=scriptable-groovy]
----

== Multiple databases

Multiple databases can be tested by using multiple DBUnit rule and Entity manager providers:

[source,java,linenums]
----
include::{testdir}/MultipleDataBasesTest.java[]
----
<1> `rule1` is the id of DataSetExecutor, the component responsible for database initialization in DBUnit Rules.
<2> here we match dataset executor id in @DataSet annotation so in this test we are going to use database from `pu1`.
<3> For multiple databases in same test we need to initialize database state `programmatically`.

== Ruling database in CDI tests

For CDI based tests we are going to use https://deltaspike.apache.org/documentation/test-control.html[DeltaSpike test control module^] and https://github.com/rmpestano/dbunit-rules/tree/master/cdi[DBUnit rules CDI^].

The first enables CDI in JUnit tests and the second enables DBUnit though a CDI interceptor.

=== Classpath dependencies

First we need DBUnit CDI:
.pom.xml
----
include::{basedir}/pom.xml[tags=dbunit-cdi]
----

And also DeltaSpike control module:

----
include::{basedir}/pom.xml[tags=test-control]
----
<1> DeltaSpike core module is base of all DeltaSpike modules
<2> Test control module api and impl
<3> CDI control OWB dependency, it is responsible for bootstraping CDI container
<4> OpenWebBeans as CDI implementation


=== Configuration
For configuration we will need a beans.xml which enables DBUnit CDI interceptor:

./src/test/resources/META-INF/beans.xml
----
include::{metainf}/beans.xml[]
----

And `apache-deltaspike.properties` to set our tests as CDI beans:

./src/test/resources/META-INF/apache-deltaspike.properties
----
include::{metainf}/apache-deltaspike.properties[]
----

The test itself must be a CDI bean so DBUnit Rules can intercept it.

The last configuration needed is to produce a EntityManager for tests:

[source,java,linenums]
----
include::{testdir}/cdi/EntityManagerProducer.java[]
----

This entityManager will be used as a bridge to JDBC connection needed by DBUnit Rules.

=== Example

Here is a test example:

[source,java,linenums]
----
include::{testdir}/cdi/DBUnitRulesCDITest.java[tags=sample]
}
----
<1> DeltaSpike JUnit runner that enables CDI in tests;
<2> The EntityManager we produced in previous steps;
<3> This annotation enables DBUnit CDI interceptor which will prepare database state before the test execution.

All other features presented earlier, *except multiple databases*, are supported by DBUnit CDI.

Here is `ExpectedDataSet` example:

.src/test/resources/datasets/expectedUsers.yml
----
include::{datasetdir}/expectedUsers.yml[]
----

And the test:

[source,java,linenums]
----
include::{testdir}/cdi/DBUnitRulesCDITest.java[tags=expectedCDI]
----

TIP: Since version _0.9.0_ (To be released at the time of writing) transactions will be able to be managed automatically at test level (useful for _expected datasets_ cause you don't assert db changes inside the test), see https://github.com/rmpestano/dbunit-rules/blob/master/cdi/src/test/java/com/github/dbunit/rules/TransactionCDIIt.java#L41[example here^].


== Ruling database in BDD tests

BDD and DBUnit are integrated by https://github.com/rmpestano/dbunit-rules#cucumber-module[DBUnit Rules Cucumber^]. It's a https://cucumber.io/[Cucumber^] runner which is CDI aware.


=== Configuration

Just add following dependency to your classpath:

.pom.xml
----
include::{basedir}/pom.xml[tags=dbunit-cucumber]
----

Now you just need to use *CdiCucumberTestRunner* to have `Cucumber`, `CDI` and `DBUnit` on your BDD tests.

=== Example

First we need a feature file:

.src/test/resources/features/search-users.feature
----
include::{featuresdir}/search-users.feature[]
----

Then a dataset to prepare our database:

.src/test/resources/datasets/usersWithTweet.json
----
include::{datasetdir}/usersWithTweet.json[]
----

Now a Cucumber runner test entry point:

[source,java,linenums]
----
include::{testdir}/bdd/DBUnitRulesBddTest.java[]
----

And finally our cucumber step definitions:

[source,java,linenums]
----
include::{testdir}/bdd/SearchUsersSteps.java[]
----

NOTE: Living documentation of _DBUnit Rules_ is based on its https://github.com/rmpestano/dbunit-rules/tree/master/cdi/src/test/java/com/github/dbunit/rules/bdd[BDD tests^], you can access it here: http://rmpestano.github.io/dbunit-rules/documentation.html.
